/**
 * Catálogo Oficial de Clientes Industriales y Corporativos de Microlabs Químicos S.A.
 * Fuente: Registro empresarial IONOS HiDrive / Expedientes de Inocuidad y Calidad de Alimentos.
 * 57 Cuentas corporativas activas verificadas.
 */

export const PRELOADED_CORPORATE_CLIENTS = [
    {
        id: 'A0001',
        name: 'ALASKA (HIELO ALASKA)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-112233',
        phone: '2234-8800',
        email: 'info@hieloalaska.com',
        code: 'A0001',
        category: 'Hielo y Agua Envasada',
        discount: 10
    },
    {
        id: 'A0002',
        name: 'ALIMENTOS PROSALUD (SARDIMAR)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-054412',
        phone: '2298-5000',
        email: 'lquiros@prosalud.com; everardo.gomez@prosalud.com',
        code: 'A0002',
        category: 'Conservas y Productos Marinos',
        discount: 15
    },
    {
        id: 'A0003',
        name: 'INV. AMPM (TIENDAS AMPM)',
        clientType: 'Supermercados',
        document: '3-101-230911',
        phone: '2528-5600',
        email: 'mramirez@ampm.co.cr; krodriguez@ampm.co.cr',
        code: 'A0003',
        category: 'Retail y Alimentos Preparados',
        discount: 12
    },
    {
        id: 'A0004',
        name: 'DISTRIBUIDORA RYS',
        clientType: 'Empresa de Alimentos',
        document: '3-101-334455',
        phone: '2272-1000',
        email: 'msoto@gruporys.com',
        code: 'A0004',
        category: 'Distribución Mayorista',
        discount: 10
    },
    {
        id: 'A0005',
        name: 'RAIN FOREST WATER RFW S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-445566',
        phone: '2239-4400',
        email: 'roy@rainforestwater.com; verny@rainforestwater.com',
        code: 'A0005',
        category: 'Agua Artesiana de Exportación',
        discount: 15
    },
    {
        id: 'A0006',
        name: 'INV. TACO BELL COSTA RICA',
        clientType: 'Restaurantes',
        document: '3-101-198822',
        phone: '2257-1822',
        email: 'aabarca@tacobell.co.cr; ksolorzano@tacobell.co.cr; nrodriguez@tacobell.co.cr',
        code: 'A0006',
        category: 'Cadenas de Comida Rápida',
        discount: 15
    },
    {
        id: 'A0007',
        name: 'INV. TURÍSTICAS TABACÓN (HOTEL TABACÓN)',
        clientType: 'Hoteles',
        document: '3-101-087766',
        phone: '2479-2000',
        email: 'ejara@tabacon.com',
        code: 'A0007',
        category: 'Hotelería y Aguas Termales',
        discount: 10
    },
    {
        id: 'A0008',
        name: 'PH PROQUIMIA',
        clientType: 'Sector Industrial General',
        document: '3-101-556677',
        phone: '2244-1100',
        email: 'aleiva@proquimia.com; haraya@proquimia.com',
        code: 'A0008',
        category: 'Productos Químicos y Desinfectantes',
        discount: 10
    },
    {
        id: 'A0009',
        name: 'SIGMA ALIMENTOS COSTA RICA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-098877',
        phone: '2437-7000',
        email: 'dcastro@sigma-alimentos.co.cr',
        code: 'A0009',
        category: 'Embutidos y Lácteos',
        discount: 15
    },
    {
        id: 'A0010',
        name: 'BIONALITICA',
        clientType: 'Sector Clínico / Privado',
        document: '3-101-776655',
        phone: '2280-1122',
        email: 'harryh2m@gmail.com; melanyz94@gmail.com',
        code: 'A0010',
        category: 'Laboratorio de Referencia',
        discount: 10
    },
    {
        id: 'B0011',
        name: 'DISA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-998877',
        phone: '2240-5566',
        email: 'noebarrantesp@gmail.com; gerenciadisa@gmail.com',
        code: 'B0011',
        category: 'Distribuidora de Alimentos',
        discount: 10
    },
    {
        id: 'B0012',
        name: 'INOLASA (ACEITES Y GRASAS)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-012345',
        phone: '2661-0022',
        email: 'jnm@inolasa.com; ksv@inolasa.com; eas@inolasa.com; ymm@inolasa.com; ecp@inolasa.com',
        code: 'B0012',
        category: 'Aceites Vegetales y Proteínas',
        discount: 15
    },
    {
        id: 'B0013',
        name: 'QUESOS ABARCA (LÁCTEOS QUETZAL)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-667788',
        phone: '2534-1122',
        email: 'g.portuguez@lacteosquetzal.com; ma.abarca@lacteosquetzal.com; m.abarca@lacteosquetzal.com; e.chanto@lacteosquetzal.com',
        code: 'B0013',
        category: 'Industria Láctea',
        discount: 10
    },
    {
        id: 'B0014',
        name: 'NUECES INDUSTRIALES S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-778899',
        phone: '2260-3344',
        email: 'inocuidad@nuecesindustriales.com',
        code: 'B0014',
        category: 'Snacks y Frutos Secos',
        discount: 10
    },
    {
        id: 'B0015',
        name: 'IND. SALQUI S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-889900',
        phone: '2276-8899',
        email: 'calidad@salqui.cr',
        code: 'B0015',
        category: 'Alimentos y Sal Industrial',
        discount: 10
    },
    {
        id: 'B0016',
        name: 'ALIMENTOS ZÚÑIGA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-990011',
        phone: '2234-9988',
        email: 'pedidos@alimentoszuniga.com',
        code: 'B0016',
        category: 'Procesamiento de Alimentos',
        discount: 10
    },
    {
        id: 'B0017',
        name: 'COOPEMONTECILLOS R.L.',
        clientType: 'Empresa de Alimentos',
        document: '3-004-045120',
        phone: '2437-1300',
        email: 'ricardo.calderon@montecillos.com; iliana.rodriguez@montecillos.com; manuel.gomez@montecillos.com; manrique.ortiz@montecillos.com',
        code: 'B0017',
        category: 'Industria Cárnica Mayorista',
        discount: 15
    },
    {
        id: 'B0018',
        name: 'ESCULTURA JADE',
        clientType: 'Sector Industrial General',
        document: '3-101-654321',
        phone: '2225-4433',
        email: 'alopez@esculturadejade.co.cr',
        code: 'B0018',
        category: 'Artesanía y Manufactura',
        discount: 5
    },
    {
        id: 'B0019',
        name: 'CONSORCIO EXPORTACIÓN SAN ANTONIO',
        clientType: 'Empresa de Alimentos',
        document: '3-101-765432',
        phone: '2440-8899',
        email: 'osequeira@sanantoniocr.com',
        code: 'B0019',
        category: 'Agroexportación',
        discount: 12
    },
    {
        id: 'B0020',
        name: 'DIALPRO (QUESOS LOS ALPES)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-876543',
        phone: '2551-7788',
        email: 'johann.latetera@gmail.com; quesoslosalpes@hotmail.com',
        code: 'B0020',
        category: 'Quesos y Derivados Lácteos',
        discount: 10
    },
    {
        id: 'C0021',
        name: 'COSTA RICA COUNTRY CLUB',
        clientType: 'Restaurantes',
        document: '3-101-001234',
        phone: '2208-5000',
        email: 'acalderon@country.co.cr',
        code: 'C0021',
        category: 'Club Social y Servicios Gastronómicos',
        discount: 10
    },
    {
        id: 'C0022',
        name: 'BRIDGESTONE / FIRESTONE',
        clientType: 'Sector Industrial General',
        document: '3-101-009988',
        phone: '2209-7000',
        email: 'VallejosElizabeth@la-bridgestone.com; MadrigalFabian@la-bridgestone.com; SalazarBrenda@la-bridgestone.com',
        code: 'C0022',
        category: 'Industria Neumática / Aguas Residuales',
        discount: 15
    },
    {
        id: 'C0023',
        name: 'VAPENSA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-987654',
        phone: '2293-1122',
        email: 'dchaves@vapensa.com',
        code: 'C0023',
        category: 'Panadería y Repostería',
        discount: 10
    },
    {
        id: 'C0024',
        name: 'TRES JOTAS',
        clientType: 'Empresa de Alimentos',
        document: '3-101-890123',
        phone: '2771-3344',
        email: 'lgodinez@tresjotas.com',
        code: 'C0024',
        category: 'Carnicería y Embutidos',
        discount: 10
    },
    {
        id: 'C0025',
        name: 'CAFÉ BRITT COSTA RICA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-098765',
        phone: '2277-1500',
        email: 'ycartin@britt.com',
        code: 'C0025',
        category: 'Cafetería, Chocolatería y Tostaduría',
        discount: 15
    },
    {
        id: 'C0026',
        name: 'FERVA DEL NORTE',
        clientType: 'Empresa de Alimentos',
        document: '3-101-789012',
        phone: '2460-1122',
        email: 'garias@fervadelnorte.com',
        code: 'C0026',
        category: 'Agroindustria',
        discount: 10
    },
    {
        id: 'C0027',
        name: 'DISTRIBUIDORA LUCEMA S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-112244',
        phone: '2272-3344',
        email: 'mgranados@lucema.com; mbarquero@lucema.com; jsolis@lucema.com; jarguello@lucema.com',
        code: 'C0027',
        category: 'Distribuidora de Alimentos',
        discount: 12
    },
    {
        id: 'C0028',
        name: 'BIOTERRA',
        clientType: 'Sector Industrial General',
        document: '3-101-678901',
        phone: '2282-5566',
        email: 'dguzman@tecnologiaem.com',
        code: 'C0028',
        category: 'Biotecnología y Agricultura',
        discount: 10
    },
    {
        id: 'C0029',
        name: 'CORP. ALGARD',
        clientType: 'Sector Industrial General',
        document: '3-101-567890',
        phone: '2236-4455',
        email: 'calidad@algard.cr',
        code: 'C0029',
        category: 'Manufactura y Envase',
        discount: 8
    },
    {
        id: 'C0030',
        name: 'SENSIENT',
        clientType: 'Empresa de Alimentos',
        document: '3-101-456789',
        phone: '2293-8899',
        email: 'calidad@sensient.com',
        code: 'C0030',
        category: 'Colorantes y Sabores Industriales',
        discount: 12
    },
    {
        id: 'D0031',
        name: 'HOTEL PLAYA TAMBOR (BARCELÓ)',
        clientType: 'Hoteles',
        document: '3-101-223355',
        phone: '2683-0303',
        email: 'higienetambor@barcelo.com',
        code: 'D0031',
        category: 'Resort y Piscinas',
        discount: 12
    },
    {
        id: 'D0032',
        name: 'CORPORACION KHAP',
        clientType: 'Sector Industrial General',
        document: '3-101-345678',
        phone: '2290-7788',
        email: 'info@khap.cr',
        code: 'D0032',
        category: 'Servicios Corporativos',
        discount: 8
    },
    {
        id: 'D0033',
        name: 'THE WESTIN RESERVA CONCHAL',
        clientType: 'Hoteles',
        document: '3-101-334466',
        phone: '2654-3444',
        email: 'inocuidad@westinconchal.com',
        code: 'D0033',
        category: 'Hotelería de Lujo / Aguas y Cocinas',
        discount: 15
    },
    {
        id: 'D0034',
        name: 'FRUVER',
        clientType: 'Empresa de Alimentos',
        document: '3-101-234567',
        phone: '2443-1122',
        email: 'calidad@fruver.co.cr',
        code: 'D0034',
        category: 'Frutas y Vegetales Procesados',
        discount: 10
    },
    {
        id: 'D0035',
        name: 'ANCYFER',
        clientType: 'Empresa de Alimentos',
        document: '3-101-123456',
        phone: '2661-3322',
        email: 'manguepez39@hotmail.com; ventas@ancyfer.com',
        code: 'D0035',
        category: 'Mariscos y Pescados Frescos',
        discount: 10
    },
    {
        id: 'D0036',
        name: 'TRANSPORTES DROUILLY',
        clientType: 'Sector Industrial General',
        document: '3-101-019283',
        phone: '2442-9988',
        email: 'logistica@drouilly.cr',
        code: 'D0036',
        category: 'Transporte Refrigerado y Cadena de Frío',
        discount: 8
    },
    {
        id: 'D0037',
        name: 'CARNES ROJAS S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-928374',
        phone: '2433-6655',
        email: 'calidad@carnesrojas.cr',
        code: 'D0037',
        category: 'Planta de Deshuese y Cárnicos',
        discount: 10
    },
    {
        id: 'D0038',
        name: 'TECNOANALÍTICA',
        clientType: 'Sector Clínico / Privado',
        document: '3-101-837465',
        phone: '2221-7788',
        email: 'soporte@tecnoanalitica.cr',
        code: 'D0038',
        category: 'Servicios de Diagnóstico',
        discount: 10
    },
    {
        id: 'D0039',
        name: 'PAN DE AZUCAR',
        clientType: 'Empresa de Alimentos',
        document: '3-101-746583',
        phone: '2283-4455',
        email: 'ventas@pandeazucar.cr',
        code: 'D0039',
        category: 'Panificación y Confitería',
        discount: 10
    },
    {
        id: 'D0040',
        name: 'LA TORRE ESPAÑOLA',
        clientType: 'Restaurantes',
        document: '3-101-658392',
        phone: '2224-3322',
        email: 'contacto@latorreespanola.cr',
        code: 'D0040',
        category: 'Restauración y Marisquería',
        discount: 8
    },
    {
        id: 'E0041',
        name: 'INTERLAB',
        clientType: 'Sector Clínico / Privado',
        document: '3-101-583920',
        phone: '2253-1199',
        email: 'microinterlab@gmail.com',
        code: 'E0041',
        category: 'Laboratorio Clínico de Enlace',
        discount: 12
    },
    {
        id: 'E0042',
        name: 'POLLO GRANJERO (CAMPERO)',
        clientType: 'Restaurantes',
        document: '3-101-445577',
        phone: '2242-8000',
        email: 'cferreto@campero.com',
        code: 'E0042',
        category: 'Cadena Restaurantes Avícolas',
        discount: 15
    },
    {
        id: 'E0043',
        name: 'COMERCIAL ARGRI (VETERINARIA)',
        clientType: 'Sector Industrial General',
        document: '3-101-392019',
        phone: '2441-5544',
        email: 'argriveterinaria@gmail.com',
        code: 'E0043',
        category: 'Salud Animal y Piensos',
        discount: 10
    },
    {
        id: 'E0044',
        name: 'ECOLAB COSTA RICA',
        clientType: 'Sector Industrial General',
        document: '3-101-556688',
        phone: '2211-7000',
        email: 'Oscar.Bogantes@ecolab.com; Yehury.Matamoros@ecolab.com',
        code: 'E0044',
        category: 'Tecnologías de Higiene y Validación 5,5,5',
        discount: 15
    },
    {
        id: 'E0045',
        name: 'ROJO FUERTE',
        clientType: 'Empresa de Alimentos',
        document: '3-101-201928',
        phone: '2430-8877',
        email: 'sara@rojofuerte.com',
        code: 'E0045',
        category: 'Salsas y Condimentos',
        discount: 10
    },
    {
        id: 'E0046',
        name: 'FRUTA SANA COSTA RICA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-192837',
        phone: '2460-4433',
        email: 'elizabethmora@frutasanacr.com',
        code: 'E0046',
        category: 'Deshidratados y Fruta Tropical de Exportación',
        discount: 12
    },
    {
        id: 'E0047',
        name: 'SERVICIOS DE PASTELERÍA (FASCR)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-928301',
        phone: '2227-6655',
        email: 'saraya@fascr.com',
        code: 'E0047',
        category: 'Pastelería y Galletería Fina',
        discount: 10
    },
    {
        id: 'E0048',
        name: 'CODEPROPE',
        clientType: 'Empresa de Alimentos',
        document: '3-101-830192',
        phone: '2771-8899',
        email: 'calidad@codeprope.cr',
        code: 'E0048',
        category: 'Cooperativa Agrícola',
        discount: 10
    },
    {
        id: 'E0049',
        name: 'QUÍMICAS MUNDIALES (QUIMUSA)',
        clientType: 'Sector Industrial General',
        document: '3-101-729182',
        phone: '2296-1100',
        email: 'control.calidad@quimusa.com; Lab@quimusa.com',
        code: 'E0049',
        category: 'Química Industrial y Limpiadores',
        discount: 12
    },
    {
        id: 'E0050',
        name: 'CETEBEDI (SOYAPAC)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-618273',
        phone: '2239-5500',
        email: 'calidad@soyapac.net',
        code: 'E0050',
        category: 'Proteínas de Soya y Bebidas Funcionales',
        discount: 12
    },
    {
        id: 'F0051',
        name: 'GLUTEN FREE (GRUPO INDUSTRIAL PAMA S.A.)',
        clientType: 'Empresa de Alimentos',
        document: '3-101-507162',
        phone: '2283-9900',
        email: 'inocuidad@grupopama.com',
        code: 'F0051',
        category: 'Alimentos Libres de Gluten y Alérgenos',
        discount: 12
    },
    {
        id: 'F0052',
        name: 'GANADERÍA MEZA LTDA (NUTRILAC / CORSOLECHERÍA)',
        clientType: 'Empresa de Alimentos',
        document: '3-102-496051',
        phone: '2553-2211',
        email: 'amorales@nutrilac.co.cr; lsedo@corsolecheria.com; acanas@nutrilac.co.cr',
        code: 'F0052',
        category: 'Producción Lechera y Quesera Especializada',
        discount: 15
    },
    {
        id: 'F0053',
        name: 'POLLOS PURA VIDA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-667799',
        phone: '2433-2211',
        email: 'planta@pollospuravida.com',
        code: 'F0053',
        category: 'Beneficio de Aves y Carne Fresca',
        discount: 12
    },
    {
        id: 'F0054',
        name: 'ALIMENTOS JACK´S CENTROAMÉRICA',
        clientType: 'Empresa de Alimentos',
        document: '3-101-007788',
        phone: '2256-4400',
        email: 'cquesada@jacks.co.cr; ogarcia@jacks.co.cr',
        code: 'F0054',
        category: 'Snacks y Botanas de Exportación',
        discount: 15
    },
    {
        id: 'F0055',
        name: 'PRODUCTOS DEL GOLFO',
        clientType: 'Empresa de Alimentos',
        document: '3-101-778811',
        phone: '2661-4455',
        email: 'productodelgolfo@hotmail.com',
        code: 'F0055',
        category: 'Pescados y Mariscos de Altura',
        discount: 12
    },
    {
        id: 'F0056',
        name: 'Freshy Dely Frescura S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-889922',
        phone: '2239-1122',
        email: 'Lbrenes@freshydeli.com',
        code: 'F0056',
        category: 'Vegetales Listos para Consumir (IV Gama)',
        discount: 12
    },
    {
        id: 'F0057',
        name: 'Congelados y Jugos del Valle Verde S.A.',
        clientType: 'Empresa de Alimentos',
        document: '3-101-384920',
        phone: '2447-1100',
        email: 'gsandino@fruitallseasons.com',
        code: 'F0057',
        category: 'Pulpas y Jugos Concentrados (Fruit All Seasons)',
        discount: 15
    }
];
